### ISSUE TITLE
PG::Error: ERROR:  missing FROM-clause entry for table "tags"

### ISSUE THREAD

**Issue by chuckweinberger** [Casecommons/pg_search#109]
I'm using pg_search 0.6.1 and RR 3.1.10.  I have been following issue #14 in hopes of being able to chain together a `pg_search_scope` with a named scope that uses `includes`.  Here's what I am trying to do: 
```  Ruby
  pg_search_scope   :with_text, 
                    :against => :title, 
                    :using => { :tsearch => { :dictionary => "english" }},
                    :associated_against => { :posts => :contents }

  scope :in_tags, lambda {|tag_array|
                            Story.includes(:tags).
                            where("tags.name in (:tag_array)", :tag_array => tag_array )
                          }

story = Story.in_tags(array_of_tags).with_text("search text goes here")
```
When I was using pg_search 5.7 I would receive the following error: `ActiveRecord::StatementInvalid: PG::Error: ERROR:  column "pg_search_rank" does not exist`.  This error is consistnet with what was reported in issue #14.  

Now that I've updated the gem to pg_search 6.1, I'm getting this error: `ActiveRecord::StatementInvalid: PG::Error: ERROR:  missing FROM-clause entry for table "tags"`.  

Note, `Story.in_tags(array_of_tags)` executes as expected.  The problem occurs only when I try to link that named scope with a `pg_search_scope`.  The order of chaining doesn't make a difference with this error

**Comment by brandoncc** [comment]
I was able to change:

```ruby
.includes(:store).where.not(stores: { tier_name: nil })
```

to:

```ruby
.joins(:store).where.not(stores: { tier_name: nil })
```

and it fixed the issue for me.

**Comment by Mackaber** [comment]
I'm also having trouble with .group() (similar to @chuckweinberger), but I'm not able to use DISTINCT since I have an aggregate function...

```ruby
User.select("users.*, COUNT(skills) AS skill_count").joins(:skills).group("users.id")
```

I'm getting a little frustrated... any help or idea will be appreciated...

**Comment by Mackaber** [comment]
Nevermind... I solved it using the hack described in  #206 by @phlegx, anyways, if it ever gets integrated I would suggest adding an option :grouped => true, to include the grouping in the search scope.

**Comment by phlegx** [comment]
Hi @Mackaber actually I use this hack:

```ruby
class << self
      # Overwrite alias method to get the right subselect alias
      def alias(*strings)
        #name = Array(strings).compact.join("_")
        # By default, PostgreSQL limits names to 32 characters, so we hash and limit to 32 characters.
        #"pg_search_#{Digest::SHA2.hexdigest(name)}"[0,32]
        Array(strings).second
      end
    end
```

Try it out and give me a feedback please. I have found many things to change in the gem. I think to do a fork.

**Comment by nertzy** [comment]
This is not an error in pg_search. Instead it's a limitation of how Active Record works with `joins` or `includes` chained with a String `where` condition.

You should use [`references`](http://www.rubydoc.info/docs/rails/4.1.7/ActiveRecord/QueryMethods:references) to ensure that the SQL `JOIN` is not built with an alias.

You can read a short description in [this Rails Guide](http://guides.rubyonrails.org/active_record_querying.html#specifying-conditions-on-eager-loaded-associations).

Here's an example of how to rewrite the `:in_tags` scope using `references`:

```ruby 
scope :in_tags, lambda { |tag_array|
  includes(:tags)
    .references("tags")
    .where("tags.name in (:tag_array)", :tag_array => tag_array )
}
```

Or, more simply, you can use a Hash which will work whether or not there are aliases:

```ruby 
scope :in_tags, lambda { |tag_array| includes(:tags).where(:tags => {:name => tag_array}) }
```

Also, you shouldn't have a reference to `Story` inside the lambda defining your scope. The default receiver is already the current class. This will help if you end up using inheritance to share this code with other classes later.

As for the other issues in this thread, it appears that many of them would probably be fixed with a call to `references` as well. If this is not the case, then please open a separate thread for each new issue.

**Comment by leofrozenyogurt** [comment]
scope :has_sizes, -> { includes(:available_sizes).where().not(available_sizes: {quantity: 0}).where("products.published IS true").where("products.inactive IS NOT true") } 


breaks the search for me
