### ISSUE TITLE
Using :order_within_rank with Multisearch

### ISSUE THREAD

**Issue by betjaminrichards** [Casecommons/pg_search#203]
I wish to use the ```:order_within_rank``` to order my results in a multisearch, however I'm not sure how to pass the information into the initializer.

Depending on the class of the object being searched I want to rank by either `published_at`, `created_at` or `updated_at`.

At the moment I have

````
PgSearch.multisearch_options = {
  using: {
    tsearch: { dictionary: "english" }
  },
  order_within_rank: "published_at DESC"
}
````

But that gives me an error because not all records have a published_at column.

Can you give me some guidance on how to configure this correctly?

**Comment by bkno** [comment]
A year ago I asked this on Stack Overflow and didn't get an answer. I've recently started looking into this again, I just tried order_within_rank within multisearchable but it doesn't seem to make any different (even with `created_at DESC`) - can anyone confirm order_within_rank works with multisearchable? Looking at my dev server log the order part of the query remains `ORDER BY pg_search_rank DESC, "pg_search_documents"."id"` but I'm not sure if there's more going on behind the scenes.

**Comment by nertzy** [comment]
That is the correct way to use `order_within_rank` with multi-search. 

But keep in mind that you need to add the `published_at` column to the `pg_search_documents` table if you want to order by it. In addition, you will need to figure out your own way of keeping the `published_at` column up-to-date with the value from your original records.

This is because of the way the multi-search works. Essentially there are callbacks on each multisearchable record that create/update the corresponding `PgSearch::Document` record which lives in the `pg_search_documents` table. And then multi-search uses a fairly straightforward pg_search_scope on `PgSearch::Document` to return results.

**Comment by siddushar** [comment]
@nertzy can you give some guidance to trigger  PgSearch::Document callbacks?
