### ISSUE TITLE
Speciying a trigram threshold, full table scan?

### ISSUE THREAD

**Issue by camallen** [Casecommons/pg_search#278]
It seems that when one adds a threshold setting to a trigram, the resulting query changes the operator from `%` to a `similarity` function, thus skipping any trgram op index on search column. 

Is this desired functionality without subsequent documentation or is this an issue with indexing for text searches in general? It'd be nice to be able to get a similarity threshold running on an index. 

For reference, setting the threshold limit globally using the `set_limit` function adds the desired behaviour but doesn't seem to be a viable solution. I've played around with using the `<->` operator ([via SO](http://stackoverflow.com/a/28546686/2761423)) but in my testing I couldn't get the resulting query to use an index either.

**Comment by nertzy** [comment]
We did some experiments with using [`set_limit()`](http://www.postgresql.org/docs/9.1/static/pgtrgm.html#PGTRGM-FUNC-TABLE) to use a threshold other than 0.3 with the `%` operator but then we found that the value set by `set_limit()` was not persisted in any meaningful way by PostgreSQL, leading to inconsistent behavior between database connections, so we removed that functionality and switched to the `similarity()` solution that you mention.

I think I remember that we also found that our indexes were not being used. We did some exploration of the C source of `pg_trgm`. What I remember is that if you use a non-default threshold, the algorithm doesn't use indexes. As far as I know, there's not a good reason for this, so it's probably something that could be fixed by someone more familiar with PostgreSQL internals. 

So since the `pg_trgm` extension does not have good first-class support for this behavior right now, we don't do anything in pg_search to support this use case.
