### ISSUE TITLE
coalesce makes indexes unusable

### ISSUE THREAD

**Issue by mmrobins** [Casecommons/pg_search#286]
Generated queries look kinda like this (simplified):

```
# explain analyze select
   "variant_search_results".*
FROM
  "variant_search_results"
WHERE
  (to_tsvector('simple', COALESCE("variant_search_results"."search_text"::text, '')) @@ to_tsquery('simple', 'Daily'::text));

                                                           QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------
 Seq Scan on variant_search_results  (cost=0.00..37973.96 rows=675 width=121) (actual time=333.201..2569.683 rows=10959 loops=1)
   Filter: (to_tsvector('simple'::regconfig, COALESCE(search_text, ''::text)) @@ '''daily'''::tsquery)
   Rows Removed by Filter: 123978
 Planning time: 0.421 ms
 Execution time: 2570.404 ms
```

If I just remove the COALESCE it uses my index

```
# \d variant_search_results
Materialized view "public.variant_search_results"
   Column    |  Type   | Modifiers
-------------+---------+-----------
 variant_id  | integer |
 search_text | text    |
Indexes:
    "variant_search_results_idx" gin (to_tsvector('simple'::regconfig, search_text))

# explain analyze select
   "variant_search_results".*
FROM
  "variant_search_results"
WHERE
  to_tsvector('simple', "variant_search_results"."search_text"::text) @@ to_tsquery('simple', 'Daily'::text)
;
                                                                 QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on variant_search_results  (cost=116.64..5536.40 rows=10921 width=121) (actual time=1.422..3.011 rows=10959 loops=1)
   Recheck Cond: (to_tsvector('simple'::regconfig, search_text) @@ '''daily'''::tsquery)
   Heap Blocks: exact=533
   ->  Bitmap Index Scan on variant_search_results_idx  (cost=0.00..113.91 rows=10921 width=0) (actual time=1.363..1.363 rows=10959 loops=1)
         Index Cond: (to_tsvector('simple'::regconfig, search_text) @@ '''daily'''::tsquery)
 Planning time: 0.213 ms
 Execution time: 3.561 ms
```
I made a simple branch that removes the coalesce https://github.com/mmrobins/pg_search/tree/remove_coalesce and it works great with the index.  Maybe removing coalesce completely isn't the right solution if some people have columns with nulls possible, but maybe there could be an option to turn it off?

**Comment by nertzy** [comment]
I originally added `coalesce` calls so that we could combine multiple columns into one string even when some of the columns were `NULL`.

It is possible to index expressions that contain calls to `coalesce`. Please read our guide for [Building Indexes](https://github.com/Casecommons/pg_search/wiki/Building-indexes) to learn more. It doesn't show the `coalesce` calls directly in its examples at the moment, but you are able to pull out expressions that contain calls to `coalesce` directly and index them, because coalesce is an "immutable" function. I have done this successfully in the past.

Feel free to reach out with any questions. I know that the documentation isn't that great about how to do this and I would appreciate any feedback on how we can make things like this easier and more discoverable.

**Comment by printercu** [comment]
@nertzy I've tried to use expression indices instead of creating separate columns for ts_vectors, and found no documentation on it in readme and wiki page from your previous message.

Here is what I came to for 2 columns:

```ruby
    # for rails 5.1
    col_exps = %w[name address].map { |x| "to_tsvector('english', COALESCE((#{x})::text, ''))" }
    add_index :buildings, "(#{col_exps.join(' || ')})",
      using: :gin, name: 'index_buildings_on_tsvector_from_english_name_address'
```

Should this be added to readme or wiki?
