### ISSUE TITLE
Wait for Release 1.0.6

### ISSUE THREAD

**Issue by isacaraujo** [Casecommons/pg_search#288]
I'm looking forward for version 1.0.6. There's some issues important issues to be released, like https://github.com/Casecommons/pg_search/commit/b80c4522fa7b18064ee7cbe732c42b6473fdc237#diff-07b3edd20fe9cc830adf1f1c5bbf48da

Thank's in advance.

**Comment by raffij** [comment]
We are also using a git version rather than gem because of changes in master.

**Comment by paratiger** [comment]
Is there any time frame for a new release or features to be added?
Can we help in any way?

**Comment by nertzy** [comment]
@paratiger Right now the build is red due to some weird issues with upstream gems. If someone can provide a pull request that gets things back to green that would be a great help.

**Comment by paratiger** [comment]
@nertzy It looks like master passes on the Ruby 2.2.3 and higher. The failures are because it always tries to install the newest gem versions.

In the development group it installs `guard-rspec`. Guard has a dependency on `listen (>= 2.7, <= 4.0)` so it attempts to install `listen 3.1.4` that requires Ruby 2.2.3 or higher.

Adding `gem 'listen', '2.7.1'` to the development group in the `Gemfile` this installs and test pass on previous Ruby versions.

I didn't want to create a PR for this as I'm not sure specifying an older gem version is what you would want. The alternative might be conditioning based on the Ruby version

**Comment by amarshall** [comment]
@nertzy The build is now green. We really should get a release out—it’s been way too long. Let me know if you want to compile release notes and do the release, else I’ll probably get to it this weekend.

**Comment by nertzy** [comment]
I'm building the release now.

**Comment by joevandyk** [comment]
should this be closed?
