### ISSUE TITLE
Can't find some two letter words

### ISSUE THREAD

**Issue by theo-bittencourt** [Casecommons/pg_search#291]
Hi! First of all, thanks for this awesome lib. ;)

We've experiencing a weird behavior when we search for two letter words (name of products).
For instance, products are found when we search for `pb`.
But there is no results when search by `tê`.

Observations:
* We are using portuguese dictionary
* "te" is a pronoun (maybe stop word for pg)

__UPDATE__

"te" word is a stop word as we expected. [(PG's portuguese stop words)](https://github.com/postgres/postgres/blob/master/src/backend/snowball/stopwords/portuguese.stop)

There is an API to customize that?

**Comment by nertzy** [comment]
Yeah that's almost certainly it.

Are you using `:ignoring => :accents`? If so, you might try turning it off because it would convert `tê` to `te` and the dictionary might be smart enough not to treat `tê` as a stop word. But then users would need to type correct diacritics to find things so that might not be a great user experience.

Also, for titles, it might be better to use the `simple` dictionary. I find that the language-specific dictionaries are more useful for paragraphs and sentences, and that the simple dictionary is better for names and titles.

Closing this issue because it's not directly an issue with pg_search.

**Comment by theo-bittencourt** [comment]
Hey @nertzy !

Yep! I'm using `ignoring: :accents`. But our users try to search by `te` (without accent) and we desire to display results for that too .

I'm searching against multiple fields. Is there some way to use `simple` dictionary __only__ for title field?
