### ISSUE TITLE
pg_search_scope multi column does not work with "only" keyword

### ISSUE THREAD

**Issue by siddharthm** [Casecommons/pg_search#371]
Hi I have a scenario where I want to search two columns of a table. For the first column (name) I want to use tsearch with prefix,dictionary and any_word enabled. For the second column (mid) I want to do exact search for the query i.e without prefix. So I used the following 

```
pg_search_scope :search, :against => [ [:name, "A"], [:mid, "B"] ], using: {
    tsearch: {
      only: [:name],
      prefix: true,
      dictionary: "english",
      any_word: true,
    }
  }
```
But when I enter a query with mid it does not display any result. If I remove the "only" keyword then I get results from mid column as well but with prefix searching enabled. Is there some issue with the plugin or am I doing something wrong?

P.S I have asked the question on [SO as well](https://stackoverflow.com/questions/46654359/pg-search-scope-multi-column-does-not-work-with-only-keyword) I looked up the community guidelines but there was nothing about raising queries. If this post is against guidelines, let know I will remove it

Thanks

**Comment by nertzy** [comment]
If I understand your goal correctly, you want a single search query to match one column exactly but the other column with prefixes.

This is not possible with pg_search today. I’m not sure whether or not it is technically possible with PostgreSQL full-text search.

By the way, the scope you posted will only match against “name” with `tsearch`. That’s the meaning of `only` in that context. It’s there so that if you wanted to, you could limit the columns that `tsearch` has access to, while another feature like `trigram` or `dmetaphone` still accesses the full set of columns. Since you only have `tsearch`, then all it does is reduce the number of columns matched.

**Comment by siddharthm** [comment]
Thanks a lot :)
