### ISSUE TITLE
Memory leak in heroku after installing

### ISSUE THREAD

**Issue by goelinsights** [Casecommons/pg_search#381]
Using the gem for multi-search.  After installing (with no other changes) seeing a memory leak that causes R14 errors in heroku without dyno resets.

Any known causes for this behavior?

**Comment by amarshall** [comment]
R14 doesn’t imply a memory leak; and, in fact, not eventually getting an R15 implies that it’s not a leak, just more memory usage. Is the memory actually steadily increasing? Does the same occur locally? Can you do profiling to see where the memory being allocated comes from? Otherwise there’s not enough information here.

**Comment by amarshall** [comment]
Closing due to lack of info.
