### ISSUE TITLE
Outdated documentation about tsvector columns

### ISSUE THREAD

**Issue by collimarco** [Casecommons/pg_search#424]
The section [Using tsvector columns](https://github.com/Casecommons/pg_search#using-tsvector-columns) in the README seems outdated. 

Now you can create an index directly on a function of the column, instead of using triggers:
https://www.postgresql.org/docs/current/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX

**Comment by nertzy** [comment]
Yes, this has always been true. We have documentation in the wiki about [creating indexes](https://github.com/Casecommons/pg_search/wiki/Building-indexes) based on expressions that call functions.

But there are some operations that, even with an index, re-evaluate the tsvector expression. Since this can be slow, many prefer to use tsvector columns.
