### ISSUE TITLE
Active Record 6.1 support

### ISSUE THREAD

**Issue by nertzy** [Casecommons/pg_search#451]
Active Record 6.1 will be released soon, and pg_search specs are not passing.

We need to figure out what changed.

See https://travis-ci.org/github/Casecommons/pg_search/jobs/741414592

**Comment by EmmaB** [comment]
I don't know if this helps, but Rails 6.1 `delegated_types` have thrown a bit of a spanner in the works. 

In the model:

```
  pg_search_scope(
    :copy_search,
      against:  :reason,
    using:              {
      tsearch: {
        dictionary: "english",
        prefix:     true,
        any_word:   true
      }
    },
    associated_against: {
      book: :isbn,
      work: :title
    }
  )
```

Previous associations:

```
  belongs_to :trackable, polymorphic: true
  belongs_to :work, foreign_key: :trackable_id, foreign_type: :work, class_name: "Work"
  belongs_to :book, foreign_key: :trackable_id, foreign_type: :book, class_name: "Book"
``` 

New Rails 6.1 associations:
```
  belongs_to :trackable, polymorphic: true
  delegated_type :trackable, types: %w[Book Work]
```

Then an error due to the table name no longer being explicit:

```undefined method `table_name' for nil:NilClass (ActionView::Template::Error)```

Sorry if this is orthogonal to the reason behind the failing specs -- I'm afraid I didn't dive in to them in detail.
